# Generated by Django 4.0.1 on 2022-05-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=56)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=56)),
                ('name', models.CharField(max_length=56)),
                ('price', models.IntegerField()),
                ('g_length', models.IntegerField()),
                ('g_width', models.IntegerField()),
                ('g_height', models.IntegerField()),
                ('s_length', models.IntegerField()),
                ('s_width', models.IntegerField()),
                ('s_height', models.IntegerField()),
                ('guarantee', models.TextField()),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
