# Generated by Django 4.0.1 on 2022-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_1',
            field=models.ImageField(upload_to='api/images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_2',
            field=models.ImageField(upload_to='api/images/'),
        ),
    ]
