# Generated by Django 4.0.4 on 2022-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_remove_user_id_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
